apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: apache
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs/
              name: apache-html
            - mountPath: /templates/
              name: apache-template
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              cp /templates/index.html /usr/local/apache2/htdocs/index.html &&
              sed -i "s/{{NODE_NAME}}/$NODE_NAME/g" /usr/local/apache2/htdocs/index.html &&
              httpd-foreground
      volumes:
        - name: apache-html
          emptyDir: {}
        - name: apache-template
          configMap:
            name: apache-hello-world
